# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: v1beta-ci

on:
  pull_request:
    branches: [ v1beta ]
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1beta

    steps:
    - uses: actions/checkout@v2
    - name: uitest
      id: uitest
      run: npm install && npm test && npm run build && tree webui-assets

    - name: Push Build Artifacts
      if: github.event_name == 'push'
      run: |
          git config user.name "Shubham Paskanti"
          git config user.email "<spaskanti1@gmail.com>"
          git add webui-assets
          git commit -m "Build Commit"
          git push origin v1beta
    - name: prmerged
      if: github.event_name == 'push'
      id: prmerged
      run: |
          echo pr has been merged and closed